# Generated by Django 2.1.1 on 2018-09-29 10:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20180929_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='articles',
            field=models.ManyToManyField(blank=True, to='articles.Article'),
        ),
        migrations.AlterField(
            model_name='group',
            name='news',
            field=models.ManyToManyField(blank=True, to='news.News'),
        ),
        migrations.AlterField(
            model_name='group',
            name='questions',
            field=models.ManyToManyField(blank=True, to='qa.Question'),
        ),
        migrations.AlterField(
            model_name='group',
            name='requests',
            field=models.ManyToManyField(blank=True, related_name='requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
