# Generated by Django 2.1.1 on 2018-09-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20180929_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='type',
            field=models.CharField(blank=True, choices=[('E', 'Event'), ('C', 'Club')], max_length=100),
        ),
    ]
