# Generated by Django 2.1.1 on 2018-09-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='secret',
            field=models.BooleanField(default=False),
        ),
    ]
